### ISSUE TITLE
Minimise latency

### ISSUE THREAD

**Issue by JonnyTech** [roc-streaming/roc-toolkit#255]
What combination of settings would produce the lowest latency? Using Alsa with an external line-in input via roc across a LAN and outputting to a roc receiver and line-out produces a minimum of 100-250 milliseconds of latencey. How can this be improved to something comparable to jackd of about 4ms?

**Comment by gavv** [comment]
Hi! Good question.

First of all, so far we have not made any serious testing on latencies below 100ms, but this is definitely must be done. The short-term plans are: control protocols, more audio encodings, and then adaptive streaming & investigating and reducing latency. If you want to help with this, you're welcome.

The overall latency is decomposed into the following components:

* on sender:

  * input latency
  * pipeline latency

* on receiver:

  * pipeline latency
  * output latency

The input or output latency (io latency) depends on the audio system being used:

* A typical robust output latency for PulseAudio is about 40ms. In case of PulseAudio, the io latency includes PulseAudio latency, ALSA latency, and the hardware latency, i.e. it is the full latency between Roc and DAC.

* In case of ALSA, Roc tools will employ SoX backend, which doesn't allow to configure the io latency directly. IIRC SoX will suggest ALSA to use the latency of `8 * internal_frame_size / num_channels` (but ALSA can choose a higher value). We have a task to implement custom ALSA backend (#231) that will allow to make the io latency on ALSA configurable directly.

The pipeline latency, off the top of my head, consists of:

* on sender: a single packet latency, equal to `packet_length`;

* on receiver: jitter/FEC buffer latency, a.k.a. "session latency"; if FEC is enabled, it should be equal to or greater than `number_of_source_packets_in_fec_block * packet_length`; if FEC is disabled, it should be equal to or greater than `packet_length`;

* on sender and receiver: resampler latency, equal to `2 * internal_frame_size / num_channels` (if resampling is enabled); the internal frame size can't be smaller than the resampler window size.

There are also two important factors:

* Round trip time. RTT/2 is the lower bound for the session latency (jitter/FEC buffer).

* Pipeline processing time. It is the lower bound for the io latency. The major part of the processing time is resampling, which speed depends on the selected resampler profile.

Here are the command-line options of interest:

* roc-send (https://roc-project.github.io/roc/docs/manuals/roc_send.html)

  * `--nbsrc`, `--nbrpr` - Number of source and repair packets per FEC block.
  * `--packet-length` - Packet size, in time units.
  * `--frame-size` - Internal frame size, in samples (total for all channels).
  * `--resampler-window` - Resampler window size, in samples (per channel). Usually it's not configured directly but is determined by `--resampler-profile`.

* roc-recv (https://roc-project.github.io/roc/docs/manuals/roc_recv.html)

  * `--sess-latency` - Target session latency, in time units. This is the size of the jitter/FEC buffer.
  * `--io-latency` - Output (playback) latency, in time units. Currently is only supported for PulseAudio.
  * `--frame-size` - Internal frame size, in samples (total for all channels).
  * `--resampler-window` - Resampler window size, in samples (per channel). Usually it's not configured directly but is determined by `--resampler-profile`.

Most of these options are also available via the C API and PulseAudio modules parameters.

Currently, the defaults are:

* PulseAudio output latency is 60ms
* suggested ALSA output latency is about 17ms on 44100Hz (44100/320/8) (but ALSA will likely choose a higher value depending on hardware)
* session latency is 200ms
* FEC block size is 20x10 packets
* packet length is 7ms
* internal frame size is 640 samples (320 samples per channel)

So, to reduce the latency, you can try this (I'd suggest to do it step-by-step):

* configure sender to use smaller FEC block size or disable FEC if you don't need it;
* configure sender to use smaller packet length;
* after this you will be able to configure receiver to use smaller session latency;
* if you use PulseAudio, configure receiver to use smaller output latency;
* if you use ALSA, configure receiver to use smaller internal frame size so that SoX will suggest ALSA a lower latency;
* configure sender and receiver to use smaller internal frame size if you want to reduce resampler latency.

It would be interesting to see the results of your experiments. BTW, how did you measure the latency?

**Comment by davex25** [comment]
[latency_examples.zip](https://github.com/roc-project/roc/files/4124107/latency_examples.zip)

Attached are some mp3 output examples of my setup, which consists of a wired connection between a source and sink, with ping times between hosts of .5 ms. Source is using sox alsa roc driver, which receives sounds via pulseaudio monitor of system output. Receiver uses wav output, frame size of 128 at varying session latencies, and resampling is not explicitly disabled (note my filenames have this wrong -- but doesn't make a noticeable difference).

Notice the artifacts when the repair port is not supplied (FEC disabled), happening on both latency examples. Also getting similar overrun counts at 20ms with and without repair port.

Let me know if I've missed something in this setup, or if I can provide any log data that could be helpful.

**Comment by gavv** [comment]
@davex25 Thanks. Could you attach exact commands you've run and roc-recv output with `-vv` option (verbose logs)? roc-send output will be probably useful too. Also, what hardware (CPU) are you using?
